### ISSUE TITLE
Describe how to install perl modules

### ISSUE THREAD

**Issue by 65156** [zimmski/filter-reply-mails#2]
Be Good if any of those perl modules were actually available/easy to find.

would be good if you could prepackage them /host them, create instructions for installing them.

**Comment by zimmski** [comment]
https://github.com/zimmski/filter-reply-mails#installation not good enough?

**Comment by 65156** [comment]
Yep half of those modules are unavailable on my repo :-1:

**Comment by zimmski** [comment]
I guess you mean a distribution repository? I am not a distribution maintainer. Add issues to the correct distribution issue tracker for missing packages. All needed perl modules are available via CPAN using a single command described in the installation section.

**Comment by 65156** [comment]
Hey zimmi, apologies as I dont use perl alot, I did install the plugins via the instructions you provided however 2 modules are unavailable, and make fails to install/compile them 

"IO::Socket::SSL" & "Mojolicious".

**Comment by 65156** [comment]
it seems its missing dependencies, Socket-1.97 for compile IO::Socket:SSL and the only version available is Socket-2.020, which fails on build.

**Comment by 65156** [comment]
ignore that, i installed some additional components, and the files are now compiling correctly 

yum install build-essential autoconf automake libtool gdb

Thanks

**Comment by 65156** [comment]
Are these errors issues?
Use of uninitialized value in sprintf at /www/data/mail-parser/filter-reply-mails/filter-reply-mails.pl line 140, <DATA> line 2231.
Use of uninitialized value in sprintf at /www/data/mail-parser/filter-reply-mails/filter-reply-mails.pl line 140, <DATA> line 2231.
VERBOSE: Connect to IMAP server with :@mail.xxx.xxx:993
VERBOSE: Open IMAP folder INBOX
IMAP select error: 1 BAD Command received in Invalid state. at /www/data/mail-parser/filter-reply-mails/filter-reply-mails.pl line 149.

**Comment by 65156** [comment]
all fixed, username was incorrect needed to encapsulate Domain\User inside of two ' , thanks mate! this is great!

**Comment by zimmski** [comment]
Well OK ;-)
