### ISSUE TITLE
Escaping Input

### ISSUE THREAD

**Issue by JukicD** [zimmski/filter-reply-mails#3]
Special characters are not escaped (e.g.: in a password).

A Password of 123&456 leads to "no command 456 was found".

**Comment by zimmski** [comment]
You need to escape your arguments according to your environment, i.e., I guess you are calling filter-reply-mails from the bash -> escape your arguments according to bash escaping.

```
# echo 1234&456
[1] 7348
1234
If '456' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf 456
[1]+  Done                    echo 1234
```
